name: echo branch Name
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.9

      - name: 버전 정보 추출(from Branch Name)
        run: echo "TAG=$(echo '${{ steps.branch-name.outputs.current_branch }}')" >> $GITHUB_ENV
        run: echo "TAG=$(echo '${{ steps.branch-name.outputs.current_branch }}' | grep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_ENV
      - name: echo current branch name
        run: echo "current branch name - ${{ env.TAG }}"